name: Python
on:
  workflow_call:
  pull_request:
    paths:
      - "src/**"
      - ".github/workflows/**"
  push:
    branches:
      - main

jobs:
  build_clang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt install libeigen3-dev
      - name: Check clang format
        run: make cppcheckformat
      - name: Clang build
        run: make clangcompile PYTHON_EXECUTABLE=${{ steps.setup-python.outputs.python-path }}

  pythonpackage:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Install CPP dependencies
        run: sudo apt install libeigen3-dev
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install building dependencies
        run: python -m pip install -r requirements.txt
      - name: Install wheel
        run: python -m pip install wheel
      - name: Install the package
        run: python -m pip install --no-build-isolation '.[dev]'
      - name: Code formatting
        run: make pyformat
      - name: Code linting
        run: make pylint
      - name: Check that stub files are up-to-date
        run: make stubgen && git diff --exit-code
      - name: Ensure all unittests(pytest) are passing
        run: make pytest